services:
  backend:
    build: ./backend
    container_name: ttc_backend
    restart: always
    network_mode: "host"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: ttc_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend