version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ttc_backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: ttc_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend